-- ============================================================
-- Rollback for v2.4.2 schema migration (0009_clear_mimic.sql).
-- This migration is additive; rollback is clean before adoption,
-- lossy after multi-document matters have been created.
--
-- PREFLIGHT GATE — READ BEFORE RUNNING.
--
-- This rollback drops all document-layer data. If any matter has
-- workflowModelVersion = 3 AND more than one document under any
-- phase, the non-first documents (ordered by createdAt) are
-- permanently deleted.
--
-- Before running, execute the preflight query:
--
--   SELECT matterId, phaseName, COUNT(*)
--   FROM documents
--   GROUP BY matterId, phaseName
--   HAVING COUNT(*) > 1;
--
-- If any rows return, this rollback is LOSSY.
-- Pass --force-lossy to the migration runner, or (preferred)
-- forward-fix instead of rolling back.
--
-- Without --force-lossy, the migration runner must refuse to
-- execute if the preflight query returns any rows.
-- If the project lacks a formal migration runner, the developer
-- must manually confirm the preflight result before executing
-- this file. Document the confirmation in the PR description.
-- ============================================================

-- Step 1: Delete feedback_manual_selections rows linked to document-scoped feedback.
DELETE FROM feedback_manual_selections
  WHERE feedbackId IN (SELECT id FROM feedback WHERE documentId IS NOT NULL);

-- Step 2: Delete document-scoped rows from extended tables.
DELETE FROM feedback_evaluations WHERE documentId IS NOT NULL;
DELETE FROM feedback WHERE documentId IS NOT NULL;
DELETE FROM versions WHERE documentId IS NOT NULL;

-- Step 3: Drop new indexes on existing tables.
-- (Names match those generated by 0009_clear_mimic.sql; adjust if Drizzle output differs.)
DROP INDEX idx_feedback_evaluations_document_version ON feedback_evaluations;
DROP INDEX idx_feedback_document_version ON feedback;
DROP INDEX idx_versions_document_latest ON versions;
DROP INDEX uniq_versions_document_version ON versions;

-- Step 4: Drop documentId columns from extended tables.
ALTER TABLE feedback_evaluations DROP COLUMN documentId;
ALTER TABLE feedback DROP COLUMN documentId;
ALTER TABLE versions DROP COLUMN documentId;

-- Step 5: Drop new tables (documents, feedback_evaluations, feedback_manual_selections).
-- feedback_evaluations and feedback_manual_selections are new in v2.4.2.
DROP TABLE IF EXISTS feedback_manual_selections;
DROP TABLE IF EXISTS feedback_evaluations;
DROP TABLE IF EXISTS documents;

-- Step 6: Drop matters.workflowModelVersion.
ALTER TABLE matters DROP COLUMN workflowModelVersion;

-- Step 7: Revert phases.workflowState enum to the v2.3 original 15-value set.
-- (Only needed if the DB enforces the enum; TiDB/MySQL may not revert automatically.)
ALTER TABLE phases MODIFY COLUMN workflowState
  ENUM(
    'idle', 'model_selection', 'processing', 'drafting', 'awaiting_selection',
    'awaiting_attorney_review', 'revising', 'reviewing', 'evaluating',
    'awaiting_decisions', 'regenerating', 'accepted', 'formatting',
    'awaiting_format_review', 'complete'
  ) NOT NULL DEFAULT 'idle';

-- Step 8: Drop the v2.4.2-added columns from phases (if they were not present in v2.3).
-- These columns were added by 0009_clear_mimic.sql to support the iterative-review
-- fields at the phase level for v2.4.2. Drop only if they did not exist in v2.3.
-- Verify against the v2.3 schema before running these statements.
ALTER TABLE phases DROP COLUMN IF EXISTS initialGeneratorModel;
ALTER TABLE phases DROP COLUMN IF EXISTS iterativeMeta;
ALTER TABLE phases DROP COLUMN IF EXISTS promptMode;

-- ============================================================
-- End of rollback.
-- ============================================================
